### ISSUE TITLE
update inhibition truncation by using 180, per Asana comment https://app.asana.com/0/0/1127967610272669/1127967610272673/f

### ISSUE THREAD

**Issue by liud4** [liud4/rVMAP#58]
https://github.com/liud4/rVMAP/blob/4dc07617a61bb49c6bc9f6ee5be279a1f31723ce/R/derive_neuropsych.R#L54

**Comment by liud4** [comment]
per Asana comment https://app.asana.com/0/0/1127967610272669/1127967610272673/f

Let's truncate np_inhibit using 180 second.

Also, per Katie's email to Dandan on 6/20/2019, we would like to derive truncated variables for np.color and np.word using 90.

**Comment by omair-a-khan** [comment]
This has been fixed before in the https://github.com/liud4/rVMAP/commit/0efcef0261ce3e452a9fa72384f800969822cb83 commit.
