### ISSUE TITLE
derive age corresponding to protocol change: https://app.asana.com/0/0/949492026778640/1205952713343853/f

### ISSUE THREAD

**Issue by liud4** [liud4/rVMAP#68]
https://github.com/liud4/rVMAP/blob/1e8aa09d639dcd810d04a8702fa163864245635a/R/derive_demographics.R#L38

For records where (!is.na(vf_arrival_date_time)) & (!(is.numeric(map.id)<=336 & epoch==1)), 

age <- floor(
      as.numeric(difftime(vf_arrival_date_time, dob, units = "days")) / days_in_one_year
    )

**Comment by panpanzhang99299** [comment]
Function "derive_demographics.R" has been updated accordingly, but errors have been reported (under investigation).
