### ISSUE TITLE
Update the calculation of fsrp.minus.age

### ISSUE THREAD

**Issue by liud4** [liud4/rVMAP#76]
https://github.com/liud4/rVMAP/blob/23ee2e5c69b2a1ec39105c6ef1c82733bf7a3d37/R/derive_fsrp.R#L174C5-L174C49

Instead of use fsrp minust fsrp.age.pts, we should simply sum up the components except for age. This will avoid missingness of fsrp.minus.age due to missing fsrp.age.pts.

 fsrp.minus.age.points <-   fsrp <- apply(
      cbind(
        fsrp.sbp.pts,
        fsrp.diabetes.pts,
        fsrp.cigs.pts,
        fsrp.cvd.pts,
        fsrp.afib.pts,
        fsrp.lvh.pts
      ),
      MARGIN = 1,
      sum
    )

**Comment by panpanzhang99299** [comment]
The "derive_fsrp" has been updated.
