### ISSUE TITLE
FSRP age extrapolation

### ISSUE THREAD

**Issue by liud4** [liud4/rVMAP#78]
https://github.com/liud4/rVMAP/blob/14f1ecb88f1a008945268e343a86601cfa70ec8e/R/derive_fsrp.R#L19

Remove " age.integer >= 54" from the code below to remove the age lower bound of fsrp.age.points derivation.

      sex == 1 & age.integer >= 54 & age.integer <= 56 ~ 0,
      sex == 2 & age.integer >= 54 & age.integer <= 56 ~ 0,

**Comment by panpanzhang99299** [comment]
The function has been updated.
