### ISSUE TITLE
Add derivation for plasma ab42 vs ab40 ratio

### ISSUE THREAD

**Issue by liud4** [liud4/rVMAP#82]
https://github.com/liud4/rVMAP/blob/c4c378f6247c8fdf6df9fd5a92b52eb31aefea52/R/derive_biomarkers.R#L202

biomarkers.ab42.ab40.ratio = biomarkers.quanterixsimoa.ab42.plasma.2022 / biomarkers.quanterixsimoa.ab40.plasma.2022

**Comment by panpanzhang99299** [comment]
csf.plasma.cobas.albumin.ratio = csf.cobas.albumin.2022 / biomarkers.cobas.albumin.plasma.2022
