### ISSUE TITLE
Add Food Scan Derivation

### ISSUE THREAD

**Issue by liud4** [liud4/rVMAP#83]
https://vumc365.sharepoint.com/:u:/r/sites/VMAC/Shared%20Documents/BoxContentMigration/VMAC%20BIOSTAT/VMAP%20Quick%20Food%20Scan%20(LF)/code/[derive_food_scan.R](https://vumc365.sharepoint.com/:u:/r/sites/VMAC/Shared%20Documents/BoxContentMigration/VMAC%20BIOSTAT/VMAP%20Quick%20Food%20Scan%20(LF)/code/derive_food_scan.R?csf=1&web=1&e=WO3A0c)?csf=1&web=1&e=WO3A0c

Do not include age.cat

**Comment by panpanzhang99299** [comment]
This function already exists, and produces same results (as in the given OneDrive).
