### ISSUE TITLE
Please add the new invalidation pipeline to NP variables on top of the existing pipeline.

### ISSUE THREAD

**Issue by liud4** [liud4/rVMAP#87]
https://github.com/liud4/rVMAP/blob/f2812e7de900ff14f0c8777cf6406f653e6646de/R/invalidate_raw_neuropsych_items.R#L15

Since Jan 2024, a new set of invalidation variables are added to REDCap database for NP invalidations. Please note the previous "manual" invalidation coded in this function (invalidate_raw_neuropsych_items.R) still applies. These invalidation only applied to new records after this implementation. 
https://app.asana.com/0/0/355060533021926/1206363512367891/f

**Comment by panpanzhang99299** [comment]
Added.
